version: '3.5'

services:
  app:
    image: pygipo:build
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DJANGO_SECRET_KEY
      - PYTHONPATH=.
      - DATABASE_URL=psql://postgres:secret@postgres/postgres
  postgres:
    image: postgres:10.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data:
    labels:
      - de.felixhummel.project=pygipo
