version: '3.1'

services:
  postgres:
    image: postgres:10.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:15432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data:
    labels:
      - de.felixhummel.project=pygipo
