
version: '3.5'

services:
  app:
    ports:
    user: ${COMPOSE_UID}:${COMPOSE_GID}
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=true
    volumes:
      - ./:/opt/project
    ports:
      - 127.0.0.1:8000:8000
    stop_signal: SIGINT
