# Generated by Django 2.0.4 on 2018-04-22 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'dump',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('entity', models.TextField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygipo.Dump')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pygipo.Record')),
            ],
            options={
                'db_table': 'record',
                'ordering': ['dt'],
            },
        ),
    ]
